version: 2
updates:
  - package-ecosystem: npm
    directory: /crm-app
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development

  - package-ecosystem: cargo
    directory: /crm-app/src-tauri
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
